// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybvhieapkzvsusxpforo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidmhpZWFwa3p2c3VzeHBmb3JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTAwODIsImV4cCI6MjA2Mjg4NjA4Mn0.reiPwDo6ttPDtO24WyJtlHJ3MWuuTv8TiyMj9ehAI1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);